### ISSUE TITLE
Updating state in effects does not trigger rerender

### ISSUE THREAD

**Issue by stratospark** [alexmingoia/purescript-pux#35]
As I experiment with timers and animations, I find that I can't replicate a basic elm animation example.

https://github.com/stratospark/pux-elm-architecture/blob/master/ex8/src/SpinSquare.purs#L64

Essentially, I'm trying to use a timer to keep on dispatching Tick actions until an animation has completed. However, I'm only seeing renders at the end of each animation cycle, not a smooth animation based on the current angle in the State. If I check the Pux Devtool, I do see that the intermediate states were recorded, but none of them triggered a render.

Any ideas? Thanks!

**Comment by alexmingoia** [comment]
Every update triggers a render. The `Tick` action is being called recursively with no delay, instead of on every animation frame. This is a problem because the math in your update function is based on the elapsed time between animation frames. In the Elm example, `Effects.tick` sends the `Tick` action on the next frame, using `requestAnimationFrame`.

I've made a pull request showing a working example: stratospark/pux-elm-architecture/pull/3
