### ISSUE TITLE
`Html` and component typing

### ISSUE THREAD

**Issue by ngasull** [alexmingoia/purescript-pux#38]
_Background: I'm kind of new to Purescript and FP in general_

While adding new pages the pux start app, I faced a runtime talking about `puxParentAction`. I had no idea where I was wrong.

```
foreign.js:28 Uncaught TypeError: Cannot read property 'puxParentAction' of undefined
```

That's only after a long debugging session in the compiled JS that I could realize that my new view did not return a react component:

``` purescript
view :: forall state action. state -> Html action
view _ = text "Hello!"
```

This perfectly compiled however, and I was convinced that using `text` from `Pux.Html` was a fair use. This has been very confusing for a beginner like me, who has at least a good knowledge of react.

`Html` is defined as follows (same for `Attributes`):

``` purescript
foreign import data Html :: * -> *
```

In my opinion, the fact that `Html` can be anything is a flaw in pux as it can easily lead to mistakes causing runtime crashes.

Considering react's architecture, we'd need some smart way to manage two kinds: elements and child elements. Indeed, the `render` function must strictly return a react component (or "null" since react 15). Child elements however can be strings or arrays.

I hope this issue makes sense, please tell me if I misunderstood anything, and thanks for your commitment in this community!

**Comment by alexmingoia** [comment]
I'm sorry you ran into this. It's a bug with the FFI implementation, where the FFI function that maps actions for `HTML` elements assumed they weren't text nodes (usually components are elements not text). It's been fixed in the latest release. Thanks for bringing this to my attention.

> In my opinion, the fact that Html can be anything is a flaw in pux as it can easily lead to mistakes causing runtime crashes.

The signature `foreign import data Html :: * -> *` does not mean that `Html` can be anything. It means that it's a foreign data type (that's why it has kind `*`) of two arguments. Ultimately, there has to be a type that maps directly to React, and that type is `Html`. Luckily, the surface area of FFI is small. Element constructors for the most part map directly to `React.createElement`.

>  Indeed, the render function must strictly return a react component (or "null" since react 15). 

Pux deals with the edge case of passing a text node to the `renderToDOM` method by wrapping it in a div.

**Comment by ngasull** [comment]
Thank you Alex for the clarifications, the foreign import signature makes sense to me now!

May I just suggest you to wrap text in a span rather than a div? I think one would expect text to render as inline and not as a block.
