### ISSUE TITLE
Config's inputs only initially runs the last input.

### ISSUE THREAD

**Issue by PipocaQuemada** [alexmingoia/purescript-pux#92]
-- | App configuration
    config :: forall eff. State -> Eff (dom :: DOM | eff) (Config State Action AppEffects)
    config state = do
     -- | Create a signal of URL changes.
    urlSignal <- sampleUrl

    -- | Map a signal of URL changes to PageView actions.
    let routeSignal = urlSignal ~> \r -> PageView (match r)

    pure
      { initialState: state
      , update: update
      , view: view
      , inputs: [  routeSignal
                , constant DummyOne  -- Note the addtional constant inputs
                , constant DummyTwo
                ]
      }

    -- | Entry point for the browser.
    main :: State -> Eff (CoreEffects AppEffects) (App State Action)
    main state = do
      app <- start =<< config state
      renderToDOM "#app" app.html
      -- | Used by hot-reloading code in support/index.js
      pure app

Given `inputs: [ routeSignal, constant DummyOne, constant DummyTwo]`, the only action initially run when you load the page will be DummyTwo, and DummyOne and PageView are never emitted.

However, if you have `inputs: [routeSignal, every second ~> const DummyOne, constant DummyTwo]`, then, while the only action to be fired initially is DummyTwo, DummyOne will be fired every second after the website is loaded.

**Comment by alexmingoia** [comment]
That is the correct functionality. The `inputs` are `Signal`s, and zipped  together using [`merge`](https://pursuit.purescript.org/packages/purescript-signal/8.0.0/docs/Signal#v:merge). A signal is a value that changes discretely over time. A function that takes two signals of a type and returns a new signal of the same type is a function which *interleaves* those discrete value changes over time. When signals are zipped a value for the resulting signal must be chosen, which in the case of [`merge`](https://pursuit.purescript.org/packages/purescript-signal/8.0.0/docs/Signal#v:merge) is the value of the first signal.

`inputs` is only for wiring up external effects. There's no use for merging constants into the application signal, since they never change after the application begins. What are you trying to accomplish with the additional input signals?

**Comment by PipocaQuemada** [comment]
> There's no use for merging constants into the application signal, since they never change after the application begins. What are you trying to accomplish with the additional input signals?

The "constant" signal that I noticed this behavior with was actually `routeSignal`.  When I added another signal in, PageView was no longer being emmited.  Reordering the signals so routeSignal is last fixes the issue, for me.

**Comment by menelaos** [comment]
@PipocaQuemada This is the same issue that was discussed in #30. Maybe that is of some help to you.
